### ISSUE TITLE
Address todo items in C# repo related to HTTP/400 PR

### ISSUE THREAD

**Issue by jasonshave** [Azure-Samples/helium-csharp#138]
The following items have been flagged in the C# repo related to the HTTP/400 error messages

- [ ] Resolve `GetMethodText` encapsulation todo for both `Actors` and `Movies`
- [ ] Investigate cleaner implementation of tests (might not need to mock certain objects to get `HttpContext`)
- [ ] Investigate alternative to `ServiceActivator` class to get `ILogger`
